spin_manifest_version = 2

[application]
name = "htmx-app"
version = "0.1.0"
authors = ["markysoft <markharrop@yahoo.com>"]
description = "learing htmx"

[[trigger.http]]
route = "/api/..."
component = "hateoas-api"

[component.hateoas-api]
source = "hateoas-api/target/hateoas-api.wasm"
allowed_outbound_hosts = ["https://www.gov.uk", "https://www.tidetimes.org.uk", "http://dataservice.accuweather.com"]
files = [{ source = "hateoas-api/src/templates", destination = "hateoas-api/src/templates" }]

[component.hateoas-api.build]
command = "npm run build"
workdir = "hateoas-api"

[[trigger.http]]
route = "/..."
component = "assets"

[component.assets]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
