spin_manifest_version = 2

[application]
name = "htmx-app"
version = "0.1.0"
authors = ["markysoft <markharrop@yahoo.com>"]
description = "learing htmx"

[[trigger.http]]
route = "/bank-holidays"
component = "bank-holidays"

[component.bank-holidays]
source = "bank-holidays/target/bank-holidays.wasm"
allowed_outbound_hosts = ["https://www.gov.uk"]

[component.bank-holidays.build]
command = "npm run build"
workdir = "bank-holidays"

[[trigger.http]]
route = "/..."
component = "assets"

[component.assets]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]
